FROM python:3.8-slim

RUN apt-get update \
   && apt-get install -y git

RUN mkdir -p /aries-backchannels
WORKDIR /aries-backchannels

COPY python/requirements.txt python/
COPY indiLynxPython/requirements-latest.txt indiLynxPython/
RUN pip install -r python/requirements.txt -r indiLynxPython/requirements-latest.txt

# Copy the necessary files from the AATH Backchannel sub-folders
COPY python python

ENV PYTHONPATH=/aries-backchannels
ENV RUNMODE=docker

ENTRYPOINT ["python", "indiLynxPython/indilynx_backchannel.py"]
