name: test-harness-findy-acapy
# RUNSET_NAME: "findy to ACA-PY"
# Scope: AIP 1.0
# Exceptions: Revocation
#
# Summary
#
# This runset uses the latest release of Aries Framework DotNet for all of the agents except Bob (holder),
# which uses the current main branch of findy-agent. The runset covers all of the AIP 1.0 tests that 
# are known to work with findy as the holder. Excluded are those tests that involve Revocation.
#
# Current
# 
# Two connection tests are passing out of Nineteen total. There are multiple issues in Issue Credential and Proof
# with dotnet as the issuer and findy as the holder.
# 
# *Status Note Updated: 2021.10.15*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "40 1 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a dotnet-master -a findy"
          TEST_AGENTS: "-d dotnet-master -b findy"
          TEST_SCOPE: "-t @AcceptanceTest -t @AIP10 -t ~@wip -t ~@revocation"
          REPORT_PROJECT: dotnet-b-findy
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: dotnet-b-findy
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
